@root_URL = http://localhost:5098

GET {{root_URL}}/weatherforecast/
Accept: application/json

###


POST {{root_URL}}/saveData
Content-Type: application/json

{
  "Id": 1
  "Name": "Jason"
  "Email": "jason@unesco.com"
}

### 
GET {{root_URL}}/GetAllPerson
Accept: application/json